"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.windowHeight = exports.windowWidth = exports.rowCount = exports.reelCount = exports.symbolType = exports.symbolHeight = exports.symbolWidth = void 0;
exports.symbolWidth = 100;
exports.symbolHeight = 100;
exports.symbolType = 9;
exports.reelCount = 5;
exports.rowCount = 5;
exports.windowWidth = 1500;
exports.windowHeight = 800;
